:: This file builds Pulse for many of the systems needed for our Pulse Unity Asset
:: Run this script from your Pulse source directory
:: It will create a new directory next to your source directory called 'dockcross-builds'
:: All builds will be placed here, and the binaries you need will be in each install directory
:: Note that for Android builds, you need to already have a completed build
:: The android protoc compiler cannot run on our linux based docker host
:: So we need to get those autogenerated files from a different build
:: You might need to add your wsl user to the sudo group
::   https://docs.microsoft.com/en-us/windows/wsl/wsl-config


:: Change to ON if you want to get libPulseJNI.so binaries
set BUILD_JAVA=OFF

cmake -DIMAGE:STRING=manylinux2014-x64 -DJAVA:BOOL=%BUILD_JAVA% -DINSTALLER:STRING="YUM" -P xcompile.cmake
::cmake -DIMAGE:STRING=android-arm -DJAVA:BOOL=%BUILD_JAVA% -DBIND:STRING=manylinux2014-x64 -P xcompile.cmake
cmake -DIMAGE:STRING=android-arm64 -DJAVA:BOOL=%BUILD_JAVA% -DBIND:STRING=manylinux2014-x64 -P xcompile.cmake
::cmake -DIMAGE:STRING=linux-x64-clang -DJAVA:BOOL=%BUILD_JAVA%
